### ISSUE TITLE
[Design / UX] Gather requirements to understand scientist/decision maker workflows

### ISSUE THREAD

**Issue by faustoperez** [NASA-IMPACT/veda-ui#1028]
### Description
In recent conversations with NASA, there is a need to target decision-makers as well as scientists on the US GHG Center website in the short-mid term.

### Acceptance criteria

- Understand the needs of the decision-maker group of users.
- List goals and expected outcomes of the US GHG Center website visit.
- Understand how the experience is different from scientific users.
- List the existing content we can surface to improve their experience.

**Comment by faustoperez** [comment]
This ticket is being reviewed together with https://github.com/US-GHG-Center/ghgc-architecture/issues/290

**Comment by aboydnw** [comment]
@faustoperez based on the meeting today, I don't think we are going to get meaningful review time from the GHG team on this topic until after R3. Should we close this out?

Alternatively, maybe we can review with @freitagb since part of this speaks to the longer term vision of the product. What do you think?

**Comment by faustoperez** [comment]
I think both options are compatible.

I am linking the Figma with the exploration work we did a few weeks ago 👉 https://www.figma.com/design/tcCUA06Knwq7nA9DUOlplo/US-GHG-Center-test-file?node-id=50-480&t=NVZ0Nn7FPw46DbOa-1 and invited @freitagb 

I'll close the ticket for now 🙂
