### ISSUE TITLE
[E & A] Update the Timeline Playheads

### ISSUE THREAD

**Issue by dzole0311** [NASA-IMPACT/veda-ui#1052]
## Context

This is the second part of https://github.com/NASA-IMPACT/veda-ui/issues/833, and includes the updating of the Timeline Playheads.

## Acceptance Criteria

- [ ] Timelines sliders and playheads function to match designs
- [ ] When the date picker floats above the date, it is spaced to not cover up the date (description in [this comment](https://github.com/NASA-IMPACT/veda-ui/pull/1048#issuecomment-2233743446))

## Related Tickets

https://github.com/NASA-IMPACT/veda-ui/issues/979

**Comment by aboydnw** [comment]
@faustoperez @dzole0311 posting a video on some thoughts relating to this ticket from testing out our recent earth.gov release. I'm not sure it's worth iterating on this at the moment but curious what you would think of this functionality

https://www.loom.com/share/f4c944de004e447baaf6c9e7f4ddd965?sid=b7997d67-7863-4d32-af87-bc36fdde481c

**Comment by faustoperez** [comment]
Good catch @aboydnw! 

I think that a simple fix would be that when users change a date using the datepicker the timeline re-centers around that date, as they're being intentional with a selection. So:

- The datepicker is used to jump between dates
- The playheads are used to indicate the date active selection and fine-tune it by manually sliding them.

The same behaviour should happen with the analysis playheads, the timeline should re-center depending on the selection.
