### ISSUE TITLE
[Design] Feature Carousel in GHG

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1084]
### Context

For GHGC R3, stakeholders would like a feature carousel on the home page to showcase urban content. They referenced the carousel nasa.gov as inspiration, where it autoprogresses every few seconds, has some calls to action to direct people to the next page, and is polished enough for the home page.

The assumption is that we can iterate on the carousel at earth.gov for this request.

### Acceptance Criteria

- A carousel can be configured on the GHGC home page with static image content
- That carousel autoprogresses
- There are call to actions within the carousel
- Users can manually move through panels in the carousel if they wish

**Comment by aboydnw** [comment]
Link to existing component in earth.gov: https://earth.gov/stories/water_resources

**Comment by faustoperez** [comment]
Here are the updated designs for the carousel feature:

<img width="4929" alt="carousel" src="https://github.com/user-attachments/assets/2bf60cd9-af67-4289-abd6-66121df70c03">

Link to Figma file 👉 https://www.figma.com/design/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?node-id=1523-5340&t=sLE1GZfxYAQJs9Ya-1

Link to prototype 👉 https://www.figma.com/proto/9INQauBWhiRxvOWDGhRrxO/US-GHG-Center?page-id=1523%3A2907&node-id=2032-30637&viewport=17%2C1209%2C0.18&t=9VQGF6IXe3Q5u689-1&scaling=min-zoom&content-scaling=fixed

Demo video:

https://github.com/user-attachments/assets/20562f5b-37ce-4235-a117-bd41d1060c5d

**How it works:**

- A large featured image stretches across the entire width of the container, showcasing the illustration of the active item.
- The active item is highlighted with a blue top border and is paired with its corresponding image.
- The rotation of elements is indicated by an animation on the blue border, which also functions as a progress bar.
- A subtle dissolve animation transitions through the three states.
- Users can pause the animation at any time by clicking on one of the cards.

**Advantages:**

- All three elements of the carousel are continuously visible.
- Since we’re not overlaying text directly on the images like traditional carousels, we have the flexibility to use a wide range of image types, not just those with high contrast.
- The design is accessible, ensuring the content is always consumable.
- It allows for multiple calls to action on a single card.

**Constraints:**

- The carousel is limited to a maximum of three items.

**Comment by hanbyul-here** [comment]
@faustoperez  
👋 Can I suggest underlining the title (a button to trigger each slide)? Such as the unstyled button from USWDS: https://designsystem.digital.gov/components/button/

**Comment by faustoperez** [comment]
> Can I suggest underlining the title (a button to trigger each slide)? Such as the unstyled button from USWDS: https://designsystem.digital.gov/components/button/

Sounds good Hanbyul!
