### ISSUE TITLE
[Refactor] Implement updated Page header / nav

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#1137]
### Context

This ticket is for a layout component as part of the VEDA refactor. This components are used to generate the overall layout and site architecture of the Dashboard. They match the overall look and feel of the app and will be used in the template instance. Our recommendation will be to use these layout components, and we anticipate that most instances will use these components, but some may decide to bring their own.

Navigation relates to the top level nav, but also any side navigation, or sub navigation found in the dataset overview page or other pages. This also depends on the design ticket #1123

This ticket might be broken down into smaller tickets after initial investigation.

**Notes:**
* Mark new files for VEDA2 refactor with `@VEDA2-REFACTOR-WORK`

### Acceptance Criteria:
- [ ] Instances are able to pull in the page header component into their existing sites
- [ ] Instances can add whatever nav links they need, in whatever order
- [ ] The updated page header uses USWDS components and styling

**Related to:** #1193

**Comment by aboydnw** [comment]
updating based on comment in #1136

**Comment by sandrahoang686** [comment]
@faustoperez @aboydnw could we also make sure to specify in these implementation or design tickets what we expect to see in the current instances alongside the template instance. As per our discussion this past Tuesday. Since again this is a "refactor" still so we need to know if the new template designs are okay being implemented and used in current instances too - more so the uswds components part and void of stuff like theming and color. This would be really helpful in helping us understand how to build certain components (either a fork or with existing components).

for example:
Page header to be implemented in template design looks like... Currently existing page header is okay to adopt this new design but maintains the same color/themes (design would be helpful for current too) 

Do you think you could specify these in these tickets and in the design work?

**Comment by aboydnw** [comment]
Pasting here the outcome of the discussion in slack, for posterity

> Our default is that we implement new designs in existing components, instead of forking. So as we release these updated components, existing instances will see small stylistic changes if they uptake the latest version of veda-ui.

> This might result in some small stylistic changes to components like the nav, footer, and others, and they might differ slightly from other features that don’t yet use USWDS styling, like the Data Catalog. Over time, all features will be updated to match USWDS styling, but that will take some time. So, instead of managing multiple forks for an extended period, we’d be better off accepting the differences.

**Comment by sandrahoang686** [comment]
![Screenshot 2024-11-12 at 12 18 17](https://github.com/user-attachments/assets/3521fcda-fc29-49de-ad6a-79b9390156ee)

Spoke with @faustoperez related to the secondary menu items and the differences between the design and what uswds offers and how to move forward from here..
Fausto mentioned it is okay to move forward with the separators and making the `Contact us` button into a link cc @AliceR

**Comment by faustoperez** [comment]
@AliceR @sandrahoang686 I updated the VEDA - USWDS Figma file with mobile designs for the header: https://www.figma.com/design/5mclPTReHcRIzKbJm8YA6a/VEDA---USWDS?node-id=753-832&t=QJiqUkeAGWMSFUoe-1

![Image](https://github.com/user-attachments/assets/41528927-245e-445b-8430-8df25009e6c3)
