### ISSUE TITLE
[REFACTOR - Bug] timelinedataset hydration on new E&A page through URL parameter not working

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#1238]
### Context
**This contents below only apply to refactored registry, not to application that use veda-ui as a submodule.** 

Timelinedataset hydration through URL parameter not working. To simply describe the issue, we are using the dataLayers from Veda faux module (already compiled, so it can be used like a dependency) to reconcile the datasets from URL parameters. : https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/exploration/atoms/datasets.ts#L54

We would need to change how we approach static datasets for this part.

#### Notes
- one of the possible solution is to make the static datasets also an atom and hydrate it so it can be used inside of other atoms? 
- I wonder if we need to consolidate how other components pass static datasets as props to standardize the dataflow once the issue above is resolved.

URL: 

Blocking a release? (y/n): 

Regression issue? (y/n):
[If yes, add Regression label]

Priority: 

### Steps to reproduce the issue

1. [Step 1 to reproduce]
2. [Step 2 to reproduce]

**Comment by aboydnw** [comment]
We've had some discussions on this ticket this week, summarizing here.

The short version is: If there is a simpler solution that would make state management easier, then let's at least propose it, even if it doesn't seem to fulfill existing requirements.

For example, right now we support the ability to refresh and have your AOIs and other selections persist. We also have a really complex AOI selection mechanism. Lastly, we support the ability for somebody to copy and paste the URL so they can share their work with somebody else. 

If there was a simpler solution that means you will lose your work on refresh, maybe we just show a dialog box warning users about refreshing. It is easy to create an AOI again and run an analysis, so that would not be the worst thing in the world.

If there is a simpler solution that means you won't be able to share the URL with your colleagues, maybe we explore another way for people to share analyses. For example, maybe they can download a file that defines the AOIs they created and even other selections like layers/dates. Then, we augment the AOI upload feature to allow for the additional information. Only to say, there are other solutions we could explore.

So, I think step 1 of this ticket should be to ask ourselves the question, if we were going to start from scratch and we knew some of these requirements were flexible, would we build this the same way? Then we can move forward from there.

**Comment by sandrahoang686** [comment]
@aboydnw did you we want to move forward with the quick solution that we came up with during our discussion to unblock this which is when a user refreshes, we just prompt them back to an empty E&A page - (or possibly prompt them back to the data selection layer modal flow) and then have a follow up with the larger discussion you mentioned above? Or would you just prefer to start that larger discussion without the quicker unblock solution?

**Comment by aboydnw** [comment]
To record the conversation during checkin:

We have a potential fix for this that wouldn't be too much to implement (1-2 days) so we plan to move forward on implementing that fix. If it starts to get out of hand or doesn't seem like a feasible solution, then we can revert back to prompting the user on refresh that all changes will be lost. Then, revisit this later on. 

In any case, we should consider reworking AOI selection in the future.
