### ISSUE TITLE
Problems with selecting whole world on the analysis page

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-ui#388]
### Three observations on the functioning of the selection of the whole world to generate an analysis:

1. When the user selects the area of the whole world to make an analysis, then if he wants to modify the shape he can only move the two upper points and cannot move the two lower points to modify the shape. 
![image](https://user-images.githubusercontent.com/111894012/207584526-f95fcd0a-ed58-4c8e-8f59-26f010d433fe.png)

2. When the user selects the area of the whole world for analysis, he can then modify the selected shape by taking part of the area of the world map to the right or left. 
This can lead to confusion about which area is the real target area. 
![image](https://user-images.githubusercontent.com/111894012/207585345-b56d6a76-555b-4d54-a899-dd43870611a7.png)

In addition, when generating the analysis in the photo where the area is shown, no portion is selected. 
![image](https://user-images.githubusercontent.com/111894012/207585782-51ec53a5-3105-47ed-b538-93e2fe4ac051.png)

Evidence: [Video ](https://www.screencast.com/t/Oa9nySSlPeaN)

3.  When the user selects the whole area of the world for analysis, it is possible to drag the map to the right or to the left and see many maps of the world consecutively, is this expected? can it remain static?

**Comment by danielfdsilva** [comment]
1) This is not expected and it should be possible to edit all points.
2) The resulting strange shapes are perhaps occurring because not all points are editable. With 1 fixed, this should be easier to avoid.
3) This is intended. World repetition is needed in case the area of interest crossed the dateline, like for example, selecting the pacific ocean. A consequence of this is that the shape repeats.
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/1090606/207596970-e6ebf78d-19f5-4004-b077-298e254dac31.png">
