### ISSUE TITLE
Feedback meeting of 2023.02.06

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#456]
This is an umbrella issue to capture notes from the feedback meeting. This needs to be distilled and converted into separate issues.

1) When a user uploads a polygon it would be good to be able to select what features to import.
2) Warn the user if they're trying to leave the analysis page while the analysis is loading (loaded data may be lost)
3) Cache analysis results so that an accidental refresh does not require all the data to be re-fetched.
4) It would be useful to be able to download the aoi as a geojson from the analysis results.
5) A list of predefined AOIs would be useful (natural earth polygons was given as example, but not all scientists rely on political boundaries)

**6. AOI simplification**  
Currently the AOI polygons are being simplified to fit in the url. It would be good to know how much common use case polygons get simplified.
Suggested using natural earth polygons and watersheds to test this.

It may be the case that having a detailed AOI is more important than be able to share the analysis through the url. To go around this it was suggested the use of a "project file" (e.g. json) that can be shared and drag-n-dropped onto the analysis page to load the parameters.

@hanbyul-here @ricardoduplos @michaelgsuttles feel free to add anything I may have missed.

**Comment by faustoperez** [comment]
Thanks Daniel, great capture, here are two additional items from my notes:

- Add a warning when a user tries to upload a too complex/too large file.
- When calculating analysis: add a cancel button, potentially a progress bar too.

**Comment by aboydnw** [comment]
Not sure if these items have been worked on since this meeting, but I created some tickets to represent this work.

- #473 
- #472 
- #405 
- #471 
- #474 

Unless commitments were made or I am misunderstanding the tone of this feedback meeting, I don't think it is critical that we address all of this feedback. We can prioritize these tickets as needed during sprint plannings.

I am going to close this ticket, though, in favor of these other tickets.
