### ISSUE TITLE
Fix look and feel of 2i2c page for AP

### ISSUE THREAD

**Issue by michaelgsuttles** [NASA-IMPACT/veda-ui#464]
We want to make whatever changes are possible to the landing page for JupyterHub to match the look and feel of the VEDA Dashboard. We will need to work with 2i2c to do this.

Original ticket is here: https://github.com/2i2c-org/infrastructure/issues/2017#issuecomment-1406702385

cc: @j08lue @ranchodeluxe (this is Greg Corradini)

**Comment by michaelgsuttles** [comment]
Next action: @j08lue can you help introduce @ricardoduplos and @faustoperez to the 2i2c folks to coordinate?

**Comment by j08lue** [comment]
I got all the details from 2i2c already. The process is straightforward.

Before we jump on redesigning that page - do we have a concept yet, how we will integrate this page into the rest of the UI? In other words, how does a user find this page? Is it envisioned to be part of the new v2 UI? Do we consider that this 2i2c hub is not the only JupyterHub / Analytics service we want to offer to our users?

Please let me know how far you are in creating a concept for that. I would also be part of informing that concept, to provide my knowledge and vision on how our Analytics offering is going to evolve.

Once we have decided that, technically, we just need to create a branch with a specific name in the 2i2c homepage template repo https://github.com/2i2c-org/default-hub-homepage and then our hub will deploy that template. Again, this is secondary to alignment of the design and overall concept, though, please.

**Comment by michaelgsuttles** [comment]
@j08lue Definitely want to think of the "bigger picture" of how it integrates into the site, but this task is for a "quick win" of fixing the page, as Manil requested. Sounds pretty straightforward--creating a new branch. @ricardoduplos and @faustoperez let us know if you need any assistance with this.

**Comment by ricardoduplos** [comment]
@michaelgsuttles I'm on it, with @danielfdsilva's help.

**Comment by ricardoduplos** [comment]
For now, we are looking to just replace the logo on this page. In order to achieve this, I need to point to the new image by updating the value of `logo_url` (line 28) on this file: https://github.com/2i2c-org/infrastructure/blob/71abaa0d91c4db1b7742a903140ae9cb2d35a480/config/clusters/nasa-veda/common.values.yaml

However, it seems that I don't have permissions to open a new branch in the [2i2c-org / infrastructure repo](https://github.com/2i2c-org/infrastructure). @j08lue, is this something you can help me with? Thanks in advance.

This is the URL for the new image: https://visex.netlify.app/graphics/nasa-veda-logo-pos.svg

**Comment by danielfdsilva** [comment]
PR is up https://github.com/2i2c-org/infrastructure/pull/2296

**Comment by ricardoduplos** [comment]
Closing this issue. New logo is up: https://nasa-veda.2i2c.cloud/hub/login?next=%2Fhub%2F
