### ISSUE TITLE
Upload custom reference layer

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-ui#479]
## Description
Based on feedback from scientists, the ability to upload a custom reference layer would be useful and would free us from having to arbitrarily pick common reference datasets to include. 

## Acceptance Criteria
- [ ] Given I am viewing a dataset exploration tab within the VEDA Dashboard, when I select to upload a custom reference layer then I am presented with the ability to select a shapefile or geojson
- [ ] Given I have selected to upload an appropriate shapefile or geojson, when I view the dataset exploration page then I am can see my uploaded file on the map as a reference layer which I can later turn off

**Comment by nerik** [comment]
@aboydnw Do we have some insights on if users would rather need layers from uploading vector shapes (with the workflow you described above) or tiled layers (raster or vector)

The latter might make more sense in the context of reference layers, and it's also arguably easier to implement at least for raster layers (one only need to specify a tileset URL, no upload whatsoever)

**Comment by aboydnw** [comment]
@nerik I get the sense that they want to upload vector shapes, but I'm not sure. Is this essentially a question of file type? If we can formulate the question really clearly, I'm thinking we can ask in the #eis-veda channel in slack and get some quick input from scientists.

**Comment by nerik** [comment]
@aboydnw The workflow we implement depends on the file type, which depends on __what the users want to see as reference layers__ along the core dataset(s) they are viewing:
- is it some specific custom satellite or drone image?
  then it's a raster layer
      --> could be hosted somewhere else and served as tiles (ask the user to provide a URL)
      --> could be a file like a GeoTIFF (not sure what we want to do in that case)
- is it a custom basemap, like USGS Topo ?
   then it's a tiled raster layer hosted somewhere else (ask the user to provide a URL)
- is it a simple polygon, like a Marine Protected Area?
   then it's a vector shape (small file that can probably be uploaded like custom AoIs)
- is it a complex polygon, like detailed state boundary?
   then it's a vector shape (but too big to be uploaded as is, user needs to be able to provide a vector tiles endpoint)
- is it multiple layers including styles etc?
   then it's probably a WMS endpoint (in which case users could provide the final raster tiles endpoint, or the WMS root endpoint and we'd need to add an interface to select layers etc)

**Comment by aboydnw** [comment]
Initial feedback from Shahryar was the "complex polygon" option. I propose we start with a simple polygon, and see if people need to upload a more complex polygon often enough to warrant adding that capability. Does this mean we would have a file size limit? 
cc @j08lue

**Comment by nerik** [comment]
The "complex polygon" is really the trickiest one:
- at some point it's not a sound idea to handle big vector files in the client. We need to put a cap on file size if we want to avoid the browser crashing etc. And if there's some actual upload involved (ie the file can be hosted on our infra), then we have to properly handle big files. On the fly simplification of the file is a possible solution (used in the AoI tool), but it's very hard to get right and might not be even desirable:
- in the context of a reference layer, precision is probably key, ie a coarse version of the precise dataset might not be useful at all. 
- then there's the question of styling: vector data does not carry style information so how do we provide some level of control to the user, if any?

That's why I think we need to scratch things a little bit more before we start implementing. It might be that a proper answer is not "adding a simple vector file" at all but maybe:
- provide a service/API to upload large vector files and serve them tiled
- or rely on the users having that already, in which case we let the option to use a vector tiles endpoint
- might be that allowing users to provide a raster tiles endpoint is a better solution (styling is embedded)
- or some WMS services that provide both raster tiles version of vector datasets + styling?

**Comment by nerik** [comment]
I suggest we implement what I described [above](https://github.com/NASA-IMPACT/veda-ui/issues/479#issuecomment-1478076211) with a few caveats:
- no styling options, just cycle through a defined color palette
- (optional) allow users to pick color and opacity for each reference layer
- hard limit on dataset size

Thoughts @aboydnw @danielfdsilva ? 
I can JFDI design, but if @ricardoduplos or @faustoperez you have some bandwidth I would love some help.

**Comment by nerik** [comment]
I suggest we implement what I described [above](https://github.com/NASA-IMPACT/veda-ui/issues/479#issuecomment-1478076211) with a few caveats:
- no styling options, just cycle through a defined color palette
- (optional) allow users to pick color and opacity for each reference layer
- hard limit on dataset size

Thoughts @aboydnw @danielfdsilva ? 
I can JFDI design, but if @ricardoduplos or @faustoperez you have some bandwidth I would love some help.

**Comment by aboydnw** [comment]
Closing ad duplicate
