### ISSUE TITLE
[E & A] - Dataset comparison

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-ui#523]
> 🙋 This issue is part of the larger [Exploration/Analysis merge component breakdown](https://github.com/NASA-IMPACT/veda-ui/issues/513). The goal is to have a discussion about this specific component and come up with implementation details/next steps.  
Check out the parent issue for a list of all components to consider.

---

## Description

Being able to compare datasets provides a very valuable layer of data exploration for the users. Currently it is only possible to enable the dataset comparison and select a date, leaving the decision of what is being compared to the dataset author.

With this new approach, the user should be able to choose what they want to compare, whether it is a dataset against itself or a list of datasets against another list.

We also have to take into account how the changes in the comparison feature affect the compare map block available in long form content (e.g. discoveries)

As for modes of comparison, currently only side-by-side is available, but other modes, like onion skin, could be considered.

## Acceptance Criteria
- [ ] There's a list of what comparison features could be included before the UX becomes too complicated
- [ ] The comparison workflow is designed and details.
- [ ] Equivalent comparison features are planned for the compare map block

**Comment by ricardoduplos** [comment]
Being able to compare datasets provides a very valuable layer of data exploration for the users. 

Users will be able to enable the comparison and select 2 different dates to view side by side, which will be the only comparison mode available.

The onion skin mode was not included because it is not a viable comparison mode when multiple datasets exist at the same time. Each dataset on the list already has an opacity option (so different raster datasets can be viewed simultaneously), therefore adding opacity on top of opacity is not viable.

As for the datasets, the list will be the same on the left and right side, just with different dates. It is not possible to compare different lists of datasets. This feature would require the interface to provide two separate timelines with separate dataset lists. The [Worldview](https://worldview.earthdata.nasa.gov) app implements this functionality, and the increased interface complexity is something that is not desirable for VEDA. Users that need this specific functionality are better off running their own comparison on a jupyter notebook, for example.

-----

We've experimented with some design approaches, but at this point nothing has provided a cohesive solution that integrates well with the rest of the UI/UX.

We are currently looking for inspiration but felt an update was due.

**Comment by danielfdsilva** [comment]
Implemented in https://github.com/NASA-IMPACT/veda-ui/pull/598
