### ISSUE TITLE
Allow for exploration of multiple datasets on same explore page 

### ISSUE THREAD

**Issue by jerikac** [NASA-IMPACT/veda-ui#616]
Mid-priority ask for the ability to add and explore multiple datasets on the explore page. Would require a feature to add datasets as a layer, and switch between datasets. _Not specific to a dataset._

**Comment by aboydnw** [comment]
@jerikac I moved this to veda-ui. I believe it is a sub-task under the current PI goal: https://github.com/NASA-IMPACT/veda-architecture/issues/286

I am sure this is already on @danielfdsilva 's radar. I don't believe we should do anything custom for GHG here, since it is already in our near term plans to include this functionality

cc @deborahUAH @Jeanne-le-Roux

**Comment by danielfdsilva** [comment]
Correct. This is part of the Analysis and Exploration merge. Work is ongoing and tracked in [this pr](https://github.com/NASA-IMPACT/veda-ui/pull/598)

Closing as duplicate
