### ISSUE TITLE
Add option to open all external links in new tabs

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-ui#873]
Some accessibility and "best practice" concerns  speak against opening all external links in new tabs.

- https://github.com/US-GHG-Center/veda-config-ghg/issues/94
- https://github.com/NASA-IMPACT/veda-ui/issues/383

However, we keep meeting this request and specifically for the U.S. GHG Center, which frequently links out to supplementary content hosted by the partner agencies, the option would be relevant to just make all external links open in new tabs. 

Can this behavior for all external links be a centralized config option in VEDA UI? Or do we need to configure it on every link in the content, unless we want to make it stick for all instances?

 - https://github.com/US-GHG-Center/veda-config-ghg/issues/315

## Acceptance criteria

- [ ] Implemented option, if possible
- [ ] Configured GHG Center instance accordingly

**Comment by sandrahoang686** [comment]
Currently, we are going to have to specify that behavior on every link in the content. This is because the overrides and components in veda-ui use the `Button` component from [our custom design library](https://github.com/developmentseed/ui-library-seed/blob/develop/packages/button/src/Button.js), for example, [here](https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/analysis/results/chart-card.tsx#L243-L249).

This button allows us to pass in the `forwardedAs` prop which extends behavior of whatever passed in, for example, `Link` (Internal route) `a tag` (external route). Because of this we can't specify this behavior in the override config file `veda.config.js` and have to do so directly where we use this component.
