### ISSUE TITLE
Bug: Search in data stories throws exception

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-ui#916]
# Description

Noticed a bug when using search on the data stories page that causes an exception.

# How to reproduce
go to https://deploy-preview-379--visex.netlify.app/stories and start typing in the search bar

# Error details
![image](https://github.com/NASA-IMPACT/veda-ui/assets/7830949/03a641d9-5226-45c6-988f-a4577a6e4250)

**Comment by j08lue** [comment]
Yeah, seems like the UI is expecting some property on the dataset (probably in the front matter) that is either null or not defined. It should ideally not fail this bad but catch that issue during build at least, so that is a bug. But I am pretty sure the issue is that the search tries to traverse incomplete dataset frontmatter.

**Comment by j08lue** [comment]
This was a data issue which I guess is resolved now.
