### ISSUE TITLE
Decision on the strategy to replace Global data exposure provided by Parcel Resolver

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/veda-ui#978]
## Context
This story came out from https://github.com/NASA-IMPACT/veda-ui/issues/896  Please read the original ticket to get the broader context. 

We could narrow down two approaches worth trying: 

1. Use Context. Expose the Provider Users to fill up this proviProvider wrap the MDX Renderer with this Provider. We should examine how SEO will be affected from this approach.

2. Get the datasets on MDX Renderer level and pass them as props. In this approach, rewriting the component so the dataset resolutions can happen on a higher container level will help avoid deep prop drilling.

Try both approaches, compare the pros and cons of each and decide which direction we are going to move forwards to.

## Acceptance Criteria

- [ ] Comparision table between the two approaches described above
- [ ] Elements to be considered in this table
   - The changes (and LOE) needed to be made on components 
   - The changes (and LOE) needed to be made on utility functions depending on faux modules (`getDatasets`... etc.)
- [ ] A decision made based on the table.

## Related Tickets

- https://github.com/NASA-IMPACT/veda-ui/issues/896 (Specifically https://github.com/NASA-IMPACT/veda-ui/issues/896#issuecomment-2129860953) 
- #800 #947

**Comment by sandrahoang686** [comment]
This is to sum the problem up more simply with context for myself as I work and think through this experiment...

**Problem**: With the new veda2 architecture, nextJs instance side and core component library, we would like to be able to pre-render  with static contents and datasets so that SEO can be maintained if not improved (SSR). The issue is that parcel-resolver served as this original role on the veda-ui side but our goal is to make the core-ui library/components agnostic of this (data-agnostic). We need decided on the best new methods in which we fetch data (parse static content) from the instance side while optimizing SSR benefits to be fed into the component ui-library or instantiated.

@hanbyul-here @dzole0311 does this capture it? lmk if i'm missing anything

**Comment by sandrahoang686** [comment]
### Goals:
* See if Datasets rendered with Javascript disabled
* Solve for Data Exposure across application => datasets were exposed across app (context) so that it can be used from any page / component.
* Solve for MDX components that depended on Datasets (MDX Renderer) => datasets were able to be passed into MDX components (for example MapBlock which currently depends on datasets from veda virtual modules)

### Notes:
* In git diffs, please look at `@EXPERIMENT-NOTE` in-line code documentation

### Experiment 1: [server-only-context](https://github.com/manvalls/server-only-context) on Instance Side 
Mix of option 1 and 2. `server-only-context` used and grabbed datasets on MDX Renderer level to pass them as props.
Use `server-only-context` lib to be able to pass in datasets across the instance app. 

**next-veda-ui branch:** `exp/context-instance-side`
**code / git diff:** https://github.com/developmentseed/next-veda-ui/compare/exp/context-instance-side?expand=1
**Takeaways:**
* 🟢 server-only-context was extremely simple and straightforward to use, it uses react cache under the hood and not react context
* 🟢 Datasets rendered with javascript disabled ✅ 
* 🟢 server side, no need for client directive
* 🔴 Datasets would have to be initialized at every new file paged based route that depended on it. Placing it higher in the tree like `RootLayout` which wraps the entire app doesn't work.
* 🟡 For mdx components that are passed through `MDXRemote` (see [here](https://github.com/developmentseed/next-veda-ui/blob/c345c6eac552322bf4aed1bb130ef3df9f7d2781/app/components/mdx.tsx#L91-L108)), we can use the library to grab datasets (that were initialized at the root of the file page based route) and pass in datasets as a prop to wrapper function which would then be passed to mdx veda-ui components. _**(note1)**_ This would require that we update the mdx components like `MapBlock` in `veda-ui` to take datasets as a prop. But then, we could remove the veda virtual modules dependency for datasets currently in the component and go towards making it data agnostic like core feature components. 

### Experiment 2: Custom Context Provider on Instance side
Mix of option 1 and 2. context used and grabbed datasets on MDX Renderer level to pass them as props.
Create custom context provider to mount high up to expose datasets across and throughout application.

**next-veda-ui branch:** `exp/custom-context-provider`
**code / git diff:** https://github.com/developmentseed/next-veda-ui/compare/exp/custom-context-provider?expand=1
**Takeaways:**
* 🟢 Can mount Provider at the highest level `RootLayout` and expose datasets down the tree
* 🟢  Because we can mount the Provider at the highest level, file page based routes can just consume the Provider to grab datasets, which for routes like data-catalog, it can grab datasets using context and then pass it directly into the veda-ui core feature component
* 🟢 Datasets rendered with javascript disabled ✅ 
* 🔴  Context can only be used client side
* 🟡 MDXRemote did not play well with context if parent components are directed with `use client` but a work around was to use context directly in the wrapper functions for the mdx components like [here](https://github.com/developmentseed/next-veda-ui/blob/78e5d06969670762635ab38b23230823d30ce7d8/app/components/mdx-components/block.tsx#L67-L73) to pass as props to mdx veda-ui component. **_(note1)_**

### Experiment 3: Custom Context Provider on UI side (Unfinished)
Create custom context provider on ui side to import into instance side. I abandoned this early on because I kept getting errors trying to import this over to the instance but overall (after speaking with Gjore as well) we thought it didn't make sense to do this. This is because the context provider would only be used on the instance side anyways and never on the ui side since veda-ui should be data agnostic. 

One thing that was brought up though (after speaking with Hanbyul, which I believe what option 1 was originally) is to have the context provider live on the ui side. We import Provider to the instance side to mount which would allow instance and veda-ui components to also then consume. MDX components like MapBlock on the veda-ui side can then just use context to grab datasets instead of relying on veda virtual modules (see [here](https://github.com/NASA-IMPACT/veda-ui/blob/4531c975cc954400b0cbd3cc53abb6a8d2c820b0/app/scripts/components/common/blocks/block-map.tsx#L3)). This was an option brought up so mentioning here. Its worth noting though that the amount of effort to go into these mdx veda-ui components to switch out veda virtual modules to use context for datasets is the same amount of effort to go in and update these take in datasets as props instead (Experiment 1 & 2). Also these mdx veda-ui components wont be data agnostic like we are making our core components.

**veda-ui branch:** `publish-lib` => `public-lib-expmt-data-exp`
https://github.com/NASA-IMPACT/veda-ui/compare/publish-lib...public-lib-expmt-data-exp?expand=1
**next-veda-ui branch:** `static-data-context-provider`
https://github.com/developmentseed/next-veda-ui/compare/exp/static-data-context-provider?expand=1

**Comment by dzole0311** [comment]
Thanks for the summary @sandrahoang686! Are the linked github branches ([this one](https://github.com/NASA-IMPACT/veda-ui/compare/publish-lib...public-lib-expmt-data-exp?expand=1) and [this one](https://github.com/developmentseed/next-veda-ui/compare/exp/static-data-context-provider?expand=1)) under the "Experiment 3" related to that experiment ("Custom Context Provider on UI side")?

**Comment by sandrahoang686** [comment]
@dzole0311 yes it is 👍🏼

**Comment by hanbyul-here** [comment]
Thanks for trying out different approaches 🙇 

From what I read, approaches 1 and 2 involve passing datasets as props to UI components. Do you see the need for control from the VEDA-UI side to decide how they should be passed? For instance, would the choice between using context or not make a significant difference as long as the datasets are appropriately conveyed to the component?

In estimating Level of Effort (LOE), was consideration given to the dependence of data-util on the faux-module? For example, utilities relying on the faux module, such as those found in this file: https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/utils/veda-data.ts , Would the effort required to replace them be similar regardless of the chosen approach?

I think a summary that focuses on replacing the VEDA faux module in VEDA-UI will be very helpful. If we are writing implementation tickets for approaches 1 and 2 or 3, what do you think will be included in each ticket?

**Comment by dzole0311** [comment]
> I think a summary that focuses on replacing the VEDA faux module in VEDA-UI will be very helpful

That would be really useful for making a decision. 

Btw, I noticed "Experiment 3: Custom Context Provider on UI side (Unfinished)" says it's unfinished -> is there something else we need to try there? 🤔

**Comment by sandrahoang686** [comment]
@hanbyul-here thanks for reviewing!

> I think a summary that focuses on replacing the VEDA faux module in VEDA-UI will be very helpful

yes, I've actually thought about this pretty early on already and have left in-line code notes/todos about it (see [here](https://github.com/NASA-IMPACT/veda-ui/blob/main/app/scripts/components/exploration/data-utils.ts#L26)). I think its best to replace the faux modules gradually as we are updating components to be data agnostic. When we update these components and notice they are calling some utility method that references datasets from the faux module. We can go in and update those utilities. I have been doing this actually with some of the data catalog work already. That will be easier to do then I think going in and doing an entire update on these util methods. We can instead focus by each component which would be easier to manually validate and test.

> From what I read, approaches 1 and 2 involve passing datasets as props to UI components. Do you see the need for control from the VEDA-UI side to decide how they should be passed? For instance, would the choice between using context or not make a significant difference as long as the datasets are appropriately conveyed to the component?

veda-ui components just need to take in datasets as a prop and shouldn't care how they are getting it (whether or not a provider is mounted high up or not shouldn't matter to them, they shouldn't use context directly in them because they should just receive as props). We should make the veda-ui components more strictly typed though I think so it will know the exact types its expecting so it can work the props.

> If we are writing implementation tickets for approaches 1 and 2 or 3, what do you think will be included in each ticket?

I can detail that after we discuss how we want to approach data exposure after our meeting

**Comment by sandrahoang686** [comment]
> Btw, I noticed "Experiment 3: Custom Context Provider on UI side (Unfinished)" says it's unfinished -> is there something else we need to try there?

@dzole0311 hmm I left comments on why it went unfinished below it. But if we decide that we would like to finish and try that experiment and there is a good reason too even after 1&2 which i think are better then we can do so after our discussion!

**Comment by sandrahoang686** [comment]
If we go with either 1 & 2, this is what it would look like
@hanbyul-here @dzole0311 
1. [Instance Prototype] Add data exposure code according to where it can go from experiment.
2. [Instance Prototype] Continue to prove out prototype by adding catalog component -> pass in props exposed from #1 and see what else it takes to integrate the data catalog sucessfully.
3. [Instance Prototype] Continue to prove out prototype by rendering static content -> pass in dataset props to mdx components that currently use faux modules. This shouldn't break anything on veda-ui when we do that on the instance side.
4. [veda-ui] Update mdx components to take in datasets as a props. THEN to support current architecture, KEEP faux modules there and have a condition to check if datasets are pass in, if not, continue to use faux modules but note in the code that it is to be removed once veda2 refactor is done. OR create a wrapper around the mdx components that call the faux modules to pass in datasets to the mdx components themselves (like what we are doing for data catalog to support current architecture).
5. [veda-ui] Continue to make core components data-agnostic and update their data-utils dependencies as we go to decouple from faux modules and to take them in as params instead.

**Comment by sandrahoang686** [comment]
Next steps
* Write down the table with pros & cons
* Make decision from it
* Create implementation POC & Implementation ticket

**Comment by sandrahoang686** [comment]
| dkfjls | Experiment 1 | Experiment 2 | Experiment 3 |
| --- | --- | --- | --- |
| Pros | <ul><li>Simple and straightforward to use, uses react cache under the hood and not react context</li><li>Datasets rendered with javascript disabled</li><li>server side, no need for client directive</li></ul> | <ul><li>Can mount Provider at the highest level RootLayout and expose datasets down the tree</li><li>Because we can mount the Provider at the highest level, file page based routes can just consume the Provider to grab datasets, which for routes like data-catalog, it can grab datasets using context and then pass it directly into the veda-ui core feature component</li><li>Datasets rendered with javascript disabled</li></ul> | <ul><li></li></ul> |
| Cons | <ul><li>Datasets would have to be initialized at every new file paged based route that depended on it. Placing it higher in the tree like RootLayout which wraps the entire app doesn't work</li></ul> | <ul><li>Context can only be used client side</li></ul> | <ul><li></li></ul> |
| Note | For mdx components that are passed through MDXRemote (see [here](https://github.com/developmentseed/next-veda-ui/blob/c345c6eac552322bf4aed1bb130ef3df9f7d2781/app/components/mdx.tsx#L91-L108)), we can use the library to grab datasets (that were initialized at the root of the file page based route) and pass in datasets as a prop to wrapper function which would then be passed to mdx veda-ui components. (note1) This would require that we update the mdx components like MapBlock in veda-ui to take datasets as a prop. But then, we could remove the veda virtual modules dependency for datasets currently in the component and go towards making it data agnostic like core feature components. | MDXRemote did not play well with context if parent components are directed with use client but a work around was to use context directly in the wrapper functions for the mdx components like [here](https://github.com/developmentseed/next-veda-ui/blob/78e5d06969670762635ab38b23230823d30ce7d8/app/components/mdx-components/block.tsx#L67-L73) to pass as props to mdx veda-ui component ([here](https://github.com/developmentseed/next-veda-ui/blob/78e5d06969670762635ab38b23230823d30ce7d8/app/components/mdx-components/block.tsx#L97)). (note1) | Text |

Based off the experiments and reviewing the Pros & Cons, I choose to move forward with **Option 2** which is creating the custom context provider on the instance side. This is because we can mount it at the highest level and call the datasets across the application/pages. We would initialize datasets at the RootLayout level, grab datasets at each page level and at the MDX renderer level where we will pass the datasets down as props to the veda-ui components. We will need the client-side directive but that will be needed nonetheless because we would need it to import the components from veda-ui (client).

Then to replace the veda faux modules from the components and utility functions, we would do this gradually as each veda-ui component is refactored to become data agnostic throughout the refactor. It doesn't make sense to do this in a bulk, an all at once PR, because then manual validation would need to cover too much surface area. I recommend starting and implementing this data exposure store with building out the data-catalog page in the instance (_a ticket for continuing to develop on instance prototype is to be made and linked here_) and I also recommend starting and implementing this data exposure store with the `MapBlock` component as well.
